//begin of DOM
$(document).ready(function() {

  var mmaFighters = ["GSP", "Daniel Cormier", "Stipe Miocic", "conor mcgregor","Tyron Woodley", "Max Holloway", "TJ Dillashaw", "Demetrious Johnson", "Chis Cyborg", "Amanda Nunes", "Rose Namajunas", "Chuck Liddell"];	

  //  create buttons based on the list of mmaFighters array
  function showButtons(){
    $("#buttons-list").empty();
    // for loop to go through  the array and create the buttomns
    // need to add class and atributes and name
    // have to append the buttons

    
    }
  }    
  
  showButtons();
  
  // ckick method
  $(document).on("click", ".mma", function() {

        //new variable will log the text data from each button
        var martialArts = $(this).html(); 
        // console.log(martialArts);

        // save the Giphy API key generated by Giphy: V84y8eRd2dBpYNfwJdjqzO0AY4MzYkkb into a variable
        // switch the protocol in the query URL from http to https, or the app may not work properly with Github Pages
        
        var queryURL = "https://api.giphy.com/v1/gifs/search?q=" + martialArts + "&api_key=V84y8eRd2dBpYNfwJdjqzO0AY4MzYkkb&limit=10";
        console.log(queryURL); // console log for testing purposes only. Can be removed
        

        // Creating an AJAX call for the specific mma fighter button that's been clicked
        $.ajax({
        url: queryURL,
        method: "GET"
        }).done(function(response) {

        var results = response.data;
            console.log(results);

            $("#movies-view").html(""); //clearns the div before adding more images

            // A for loop to create divs with fighters images
            
            // Gets ratings for each mmafigher image
               
            } 

    }); 

            //function to stop and animate mma fighters' images
           
    } //end of on click function

  }); //end of document on click 

   //adding new button to array
        $(document).on("click", "#add-fighter", function(){
           
            }

        });
                      

}); // end of DOM

