//begin of DOM
$(document).ready(function() {

  var mmaFighters = ["GSP", "Daniel Cormier", "Stipe Miocic", "conor mcgregor","Tyron Woodley", "Max Holloway", "TJ Dillashaw", "Demetrious Johnson", "Chis Cyborg", "Amanda Nunes", "Rose Namajunas", "Chuck Liddell"];	

  //  function declaration that create buttons based on the list of mmaFighters array
  function showButtons(){
    $("#button-list").html("");
    // for loop to go through the array and create the buttomns
    // need to add class and atributes and name
    // have to append the buttons in the webpage

    for (var i = 0; i < mmaFighters.length; i++) {
      var createButton = $("<button>");

      createButton.addClass("mma");
      createButton.attr("data-name", mmaFighters[i]);
      createButton.text(mmaFighters[i]);
      $("#buttons-list").append(createButton);
    }
  }    
  
  showButtons();
  
  // click method
  $(document).on("click", ".mma", function() {

        var martialArts = $(this).html(); 
        console.log(martialArts); // returns the fither name. console log for testing purposes only. Can be removed

        // save the Giphy API key generated by Giphy: V84y8eRd2dBpYNfwJdjqzO0AY4MzYkkb into a variable
        // switch the protocol in the query URL from http to https, or the app may not work properly with Github Pages
        
        var queryURL = "https://api.giphy.com/v1/gifs/search?q=" + martialArts + "&api_key=V84y8eRd2dBpYNfwJdjqzO0AY4MzYkkb&limit=10";
        console.log(queryURL); // console log for testing purposes only. Can be removed
        
        /* AJAX call for the mma fighter selected when a button has been clicked and returns
        all the details pertained to that fighter */

        $.ajax({
        url: queryURL,
        method: "GET"
        }).done(function(response) {

        var fighterResult = response.data;
            console.log(fighterResult); // returns all fighter's detail from Giphy

            $("#fighters-view").html(""); //clearns the div before adding more images

            // A for loop to create divs with fighters images
            for ( var j=0; j < results.length; j++) {
              var imageDiv = $("<div>");
              var imageView = fighterResult[j].images.fixed_height.url;
              var still = fighterResult[j].images.fixed_height_still.url;
              //console.log(imageView);  // console log for testing purposes only. Can be removed

              var image = $("<img>").attr("src", still).attr("data-animate", imageView).attr("data-still", still);
                  image.attr("data-state", "still");
                  $("#movies-view").prepend(image);
                  image.on("click", playGif);

              // Gets ratings for each movie
              var rating = results[j].rating;
                 //  console.log(rating);// console log for testing purposes only. Can be removed

              var displayRated= $("<p>").text("Rating: " + rating);
              $("#movies-view").prepend(displayRated);
               
            } 

    }); 

            //function to stop and animate mma fighters' images
           
    } //end of on click function

  }); //end of document on click 

   //adding new button to array
        $(document).on("click", "#add-fighter", function(){
           
            }

        });
                      

}); // end of DOM

